@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTEyODEwMDV9.EcFhDq4oST57tcy2SPle5NVmboz5e4mjUywhDORdAN8

### Favorites Index
GET http://localhost:3000/favorites

### Favorites Create
POST http://localhost:3000/favorites/
Content-Type: application/json

{
"user_id": 4,
"plant_id": 11
}

### Favorites Show
GET http://localhost:3000/favorites/11

### Plants Index
GET http://localhost:3000/plants


### User Create (sign-up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}