@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NTE3ODE2Nzd9.6VG-HZ7_lEXkLaeVsXiM0sYiVA3mZ36-_DwutsaBbf0

### Favorites Index
GET http://localhost:3000/favorites

### Favorites Create
POST http://localhost:3000/favorites/
Content-Type: application/json

{
"user_id": 4,
"plant_id": 11
}


### Favorites Destroy
DELETE http://localhost:3000/favorites/

### Plants Index
GET http://localhost:3000/plants

### Plants Show
GET http://localhost:3000/plants/11

### User Create (sign-up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Twilio Create
GET http://localhost:3000/twilio/sms/
# Content-Type: application/json