# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
User.create(name: "Norman Bates", email: "batesmotel@test.com", password: "password")
User.create(name: "Sweeney Todd", email: "suchawaste@test.com", password: "password")
User.create(name: "Hannibal Lecter", email: "favabeans@test.com", password: "password")




Plant.create(name: "Asparagus Fern", description: "Although it's neither asparagus nor fern, this plant has been popular for decades. Don't let the feathery foliage deceive you - the plant is thorny and poisonous if eaten.Nonetheless, it's indestructible and brings a unique texture to your windowsill. As long as it has plenty of water and light, it'll thrive as a climbing, trailing or upright plant. In fact, asparagus ferns grows so vigorously it's considered a weed in the wild.", image_url: "https://cdn.shopify.com/s/files/1/0552/5644/9180/products/greenparadise-foxtail-fern.jpg?v=1616154966")
Plant.create(name: "Monstera", description: "Monstera is a jungle vine famous for the 'Swiss cheese' holes in its mature leaves. It's fast-growing even in low light conditions and can tolerate some neglect when it comes to watering and feeding. Just be careful not to overwater it. This is a statement plant for beginners. The only thing to bear in mind is that it needs extra dusting and some pruning to keep it looking its best.", image_url: "https://www.plantvine.com/plants/Monstera-Deliciosa4.jpg")
Plant.create(name: "Maranta Prayer Plant", description: "Maranta is also known as a prayer plant. The most popular varieties have red-veined or tricolor leaves. It's not too hard to keep alive, but it's high maintenance if you want it to look healthy long term. If you overwater, forget to mist it to raise the humidity, or forget to feed it, the tips of the leaves will turn irrevocably brown.", image_url: "https://www.thespruce.com/thmb/nrCY_hj4ssk8kim9_orRYXNevmc=/1348x900/filters:fill(auto,1)/grow-maranta-inside-1902647-02-de777eb8e7804c3d86d658cd242583d6.jpg")
Plant.create(name: "Fiddle Leaf Fig", description: "The fiddle leaf is not a plant for beginners. It's sensitive to drafts and temperature changes, requires humidity to thrive and is fussy about getting enough of the right kind of indirect light. If it's not satisfied, it'll take many years to grow tall. There's a reason the mature trees are so eye-wateringly expensive.", image_url: "https://www.gardeningknowhow.com/wp-content/uploads/2018/02/fiddle-leaf-fig.jpg")
Plant.create(name: "Alocasia", description: "The Alocasia aka elephant ear plant has dark, strikingly-shaped leaves with contrasting veins. It's happy to grow in low light but does need higher humidity than most homes can provide. Because of this, and its needs for regular dusting, feeding and pest control, it can be quite high maintenance.", image_url: "https://cdn.shopify.com/s/files/1/0212/1030/0480/products/alocasia-polly_1_x560.png?v=1627144339")
Plant.create(name: "Air Plant", description: "Because air plants don't need soil or a watering can, they have a reputation for being zero maintenance. The truth is that they need good air circulation, regular misting with distilled water, bright light and constant temperatures to keep them happy. Even then they might still die without warning. This is a beautiful family of plants to collect if you can put the effort in.", image_url: "https://www.sunset.com/wp-content/uploads/group-of-air-plants-Getty-0621.jpg")
Plant.create(name: "Dragon Tree", description: "The dragon tree plant is usually sold as a small, statement tree with bursts of thin leaves at the top of the straight trunk. It needs a spot where it can have moderate light but not direct summer sun, as well as regular watering. Like the other long-leaved indoor plants on this list, this plant is easy-care but hard to maintain as a perfect specimen.", image_url: "https://cdn.shopify.com/s/files/1/0068/4215/5090/t/115/assets/f34f50554737--pl-RedDracaenaMarginata-6IN-po-grower-detail-1_480x_crop_center.jpg?v=1628292294")
Plant.create(name: "Anthurium", description: "Some people confuse this plant with a peace lily, but they're different. Anthurium plants don't need a lot of water and tolerates low light but more sun will give you more of its long-lasting scarlet flowers. The only extra attention it needs is a little orchid mix in its soil when you're repotting.", image_url: "https://images.fineartamerica.com/images-medium-large/heart-antherium-rosalie-scanlon.jpg")
Plant.create(name: "", description: "", image_url: "")
Plant.create(name: "", description: "", image_url: "")